"""
Module 4.1 — 3D CFD validation (v2).

For a BO winner produced by Module 3.1 we re-run both solvers at higher
fidelity (3D) on the same parametric geometry used during 2D BO.  The key
number the manuscript quotes is

    ΔL² = L2_to_target(3D) − L2_to_target(2D)

If ΔL² ≲ 10% in relative terms the 2D-during-BO approximation is validated;
if it is larger, the BO of that target profile would need to be re-run in 3D
(Development Guide v2 §8).  WSS diagnostics are retained as a flow-field
sanity check (matching the v1 2D-vs-3D comparison used in the premise test).

Geometry
--------
The 3D blockMesh is generated by
``ooc_optimizer.geometry.generate_blockmesh_dict_v2_3d`` with configurable
``nz`` (number of z-layers) and ``z_grading`` (end/start ratio; < 1
concentrates cells near the floor to resolve the floor WSS boundary layer).
``snappyHexMesh`` with a 5-layer boundary layer addition can replace the
blockMesh path via ``use_snappy=True``; the fallback blockMesh keeps the
validation self-contained when no STL is available.

This module is intentionally separate from :mod:`ooc_optimizer.validation.cfd_3d`
(which still serves the v1 WSS premise test) to keep each script single-
purpose and to decouple the v1 retention path from v2 feature work.
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import subprocess
import textwrap
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

from ooc_optimizer.cfd.foam_parser import (
    find_latest_time,
    read_cell_centres,
    read_scalar_field,
    read_vector_field,
)
from ooc_optimizer.cfd.scalar import (
    DEFAULT_DIFFUSIVITY_M2_S,
    _find_openfoam_prefix,
    run_scalar_transport,
)
from ooc_optimizer.geometry import generate_blockmesh_dict_v2_3d
from ooc_optimizer.optimization.objectives import (
    TargetProfile,
    build_target_profile,
    l2_to_target,
)

logger = logging.getLogger(__name__)

SOLVER_TIMEOUT_S = 1800  # 30 min is the per-stage ceiling for 3D


@dataclass
class Result3D:
    """Summary of one 3D validation run."""

    case_dir: Path
    winner_spec: Dict[str, Any]
    L2_to_target_3d: float
    L2_to_target_2d: Optional[float]
    L2_relative_delta: Optional[float]
    tau_floor_mean_3d: float
    tau_floor_max_3d: float
    tau_floor_cv_3d: float
    wall_time_s: float
    converged_U: bool
    converged_C: bool
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "case_dir": str(self.case_dir),
            "winner_spec": dict(self.winner_spec),
            "L2_to_target_3d": float(self.L2_to_target_3d),
            "L2_to_target_2d": None if self.L2_to_target_2d is None else float(self.L2_to_target_2d),
            "L2_relative_delta": (
                None if self.L2_relative_delta is None else float(self.L2_relative_delta)
            ),
            "tau_floor_mean_3d": float(self.tau_floor_mean_3d),
            "tau_floor_max_3d": float(self.tau_floor_max_3d),
            "tau_floor_cv_3d": float(self.tau_floor_cv_3d),
            "wall_time_s": float(self.wall_time_s),
            "converged_U": bool(self.converged_U),
            "converged_C": bool(self.converged_C),
            "warnings": list(self.warnings),
        }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def validate_winner_3d(
    *,
    winner: Dict[str, Any],
    config: Dict[str, Any],
    target_profile_spec: Dict[str, Any],
    output_dir: Path,
    nz: int = 25,
    z_grading: float = 1.0,
    base_nx: int = 300,
    ny_per_mm: int = 30,
    diffusivity_m2_s: Optional[float] = None,
) -> Result3D:
    """Run a full 3D simpleFoam + scalarTransportFoam validation for one winner.

    Parameters
    ----------
    winner : dict
        The ``best_feasible`` record produced by Module 3.1 (or a dict with
        ``params``, ``topology``, ``pillar_config``, ``H``).
    config : dict
        Loaded YAML config (needs ``fixed_parameters`` and ``paths``).
    target_profile_spec : dict
        Target profile spec (same keys as the YAML ``target_profile`` block).
    output_dir : Path
        Parent directory for the 3D case; one subdirectory is created per run.
    nz : int
        Number of z-cells for the 3D mesh.
    z_grading : float
        blockMesh simpleGrading z end/start ratio (< 1 → cells near floor).
    base_nx, ny_per_mm : int
        Lateral mesh resolution.
    diffusivity_m2_s : float, optional
        Override the config's default DT; required if the v1 config has no
        ``diffusivity`` key.
    """
    params = dict(winner["params"])
    topology = winner.get("topology", winner.get("inlet_topology"))
    if topology is None:
        raise ValueError("winner must carry 'topology' or 'inlet_topology'")
    pillar_config = winner.get("pillar_config", "none")
    H_um = float(winner.get("H", 200.0))
    if pillar_config != "none":
        # For 3D validation in this module we support blockMesh-only; pillar
        # cases would need snappyHexMesh which is handled by the CFD
        # orchestrator in module 2.2 (not repeated here to keep scope tight).
        logger.warning(
            "3D validation with pillar_config=%s is not supported via blockMesh; "
            "the winning geometry is meshed without pillars.", pillar_config,
        )

    target_profile = build_target_profile(dict(target_profile_spec))
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    case_name = f"3d_{topology}_H{int(H_um)}_{int(time.time()*1000)}"
    case_dir = output_dir / case_name

    mu = float(config["fixed_parameters"]["fluid_viscosity_Pa_s"])
    rho = float(config["fixed_parameters"].get("fluid_density_kg_m3", 1000.0))
    if diffusivity_m2_s is None:
        diffusivity_m2_s = float(config.get("diffusivity", DEFAULT_DIFFUSIVITY_M2_S))

    # --- stage case ------------------------------------------------------
    template_dir = Path(config["paths"]["template_case"])
    if case_dir.exists():
        shutil.rmtree(case_dir)
    shutil.copytree(template_dir, case_dir)

    bm = generate_blockmesh_dict_v2_3d(
        params=params,
        topology=topology,
        H_um=H_um,
        base_nx=base_nx,
        ny_per_mm=ny_per_mm,
        nz=nz,
        z_grading=z_grading,
    )
    (case_dir / "system" / "blockMeshDict").write_text(bm.content)

    Q_total_m3s = float(params["Q_total"]) * 1e-9 / 60.0
    r_flow = float(params["r_flow"])
    U_drug = (r_flow * Q_total_m3s) / max(bm.inlet_drug_area_m2, 1e-20)
    U_medium = ((1.0 - r_flow) * Q_total_m3s) / max(bm.inlet_medium_area_m2, 1e-20)
    drug_vec = (0.0, U_drug, 0.0) if topology == "asymmetric_lumen" else (U_drug, 0.0, 0.0)
    medium_vec = (U_medium, 0.0, 0.0)

    _write_u_field_3d(case_dir / "0" / "U", drug_vec, medium_vec)
    _write_p_field_3d(case_dir / "0" / "p")
    _write_t_field_3d(case_dir / "0" / "T")

    # --- momentum solve --------------------------------------------------
    start = time.perf_counter()
    if not _run_blockmesh_3d(case_dir):
        raise RuntimeError(f"blockMesh failed for 3D case {case_dir}")
    converged_U = _run_simplefoam_3d(case_dir)
    if not converged_U:
        logger.warning("3D simpleFoam failed to meet residuals for %s", case_dir.name)

    # --- scalar solve ----------------------------------------------------
    # Add wallShearStress function object + cell centres before the scalar
    # overwrites controlDict.
    _run_postprocess(case_dir, "writeCellCentres")
    wall_shear_ok = _run_postprocess(case_dir, "wallShearStress", ignore_errors=True)
    scalar_result = run_scalar_transport(
        case_dir=case_dir,
        diffusivity_m2_s=diffusivity_m2_s,
        c_drug=1.0,
        c_medium=0.0,
        patches={
            "inlet_drug": "fixedValue:1",
            "inlet_medium": "fixedValue:0",
            "outlet": "zeroGradient",
            "walls": "zeroGradient",
            "floor": "zeroGradient",
            "ceiling": "zeroGradient",
        },
    )
    wall_time_s = time.perf_counter() - start

    # --- metrics ---------------------------------------------------------
    L2_3d = _compute_l2_floor_3d(case_dir, target_profile, bm.chamber_length_m, bm.chamber_width_m)
    tau_mean, tau_max, tau_cv = _floor_wss_statistics(case_dir, mu)

    L2_2d = None
    if "L2_to_target" in (winner.get("metrics") or {}):
        L2_2d = float(winner["metrics"]["L2_to_target"])
    elif "L2_to_target" in winner:
        L2_2d = float(winner["L2_to_target"])
    rel_delta = None
    if L2_2d is not None and L2_2d > 1e-12:
        rel_delta = (L2_3d - L2_2d) / L2_2d

    return Result3D(
        case_dir=case_dir,
        winner_spec={
            "params": params,
            "topology": topology,
            "pillar_config": pillar_config,
            "H": H_um,
            "target_profile": target_profile_spec,
        },
        L2_to_target_3d=float(L2_3d),
        L2_to_target_2d=L2_2d,
        L2_relative_delta=rel_delta,
        tau_floor_mean_3d=tau_mean,
        tau_floor_max_3d=tau_max,
        tau_floor_cv_3d=tau_cv,
        wall_time_s=wall_time_s,
        converged_U=bool(converged_U),
        converged_C=bool(scalar_result.converged),
        warnings=list(scalar_result.warnings) + ([] if wall_shear_ok else ["wallShearStress unavailable"]),
    )


def validate_all_winners(
    *,
    orchestrator_results: Dict[str, Any],
    config: Dict[str, Any],
    output_dir: Path,
    **kwargs: Any,
) -> List[Result3D]:
    """Run ``validate_winner_3d`` on every winner from a multi-target sweep.

    Expects the dict returned by
    ``ooc_optimizer.optimization.run_multi_target_workflow``: one primary
    winner plus zero or more secondary winners.  Each gets its own 3D case.
    """
    all_winners: List[Dict[str, Any]] = []
    primary = orchestrator_results.get("primary") or {}
    pw = primary.get("winner")
    if pw is not None:
        pw = dict(pw)
        pw["target_profile"] = pw.get("target_profile") or orchestrator_results.get("primary_target_profile")
        all_winners.append(pw)
    for sec in orchestrator_results.get("secondary", []) or []:
        sw = sec.get("winner")
        if sw is not None:
            sw = dict(sw)
            sw["target_profile"] = sec.get("target_profile")
            all_winners.append(sw)

    out: List[Result3D] = []
    for w in all_winners:
        spec = w.get("target_profile") or {"kind": "linear_gradient"}
        logger.info("3D validation for winner %s (target=%s)", w.get("config_name"), spec)
        res = validate_winner_3d(
            winner=w,
            config=config,
            target_profile_spec=spec,
            output_dir=Path(output_dir),
            **kwargs,
        )
        out.append(res)
    return out


# ---------------------------------------------------------------------------
# OpenFOAM helpers (3D)
# ---------------------------------------------------------------------------


def _write_u_field_3d(path: Path, drug_vec, medium_vec) -> None:
    path.write_text(
        textwrap.dedent(
            f"""\
            FoamFile
            {{
                version     2.0;
                format      ascii;
                class       volVectorField;
                object      U;
            }}

            dimensions      [0 1 -1 0 0 0 0];
            internalField   uniform (0 0 0);

            boundaryField
            {{
                inlet_drug
                {{
                    type            fixedValue;
                    value           uniform ({drug_vec[0]:.6f} {drug_vec[1]:.6f} {drug_vec[2]:.6f});
                }}
                inlet_medium
                {{
                    type            fixedValue;
                    value           uniform ({medium_vec[0]:.6f} {medium_vec[1]:.6f} {medium_vec[2]:.6f});
                }}
                outlet   {{ type zeroGradient; }}
                walls    {{ type noSlip;        }}
                floor    {{ type noSlip;        }}
                ceiling  {{ type noSlip;        }}
            }}
            """
        )
    )


def _write_p_field_3d(path: Path) -> None:
    path.write_text(
        textwrap.dedent(
            """\
            FoamFile
            {
                version     2.0;
                format      ascii;
                class       volScalarField;
                object      p;
            }

            dimensions      [0 2 -2 0 0 0 0];
            internalField   uniform 0;

            boundaryField
            {
                inlet_drug   { type zeroGradient; }
                inlet_medium { type zeroGradient; }
                outlet       { type fixedValue; value uniform 0; }
                walls        { type zeroGradient; }
                floor        { type zeroGradient; }
                ceiling      { type zeroGradient; }
            }
            """
        )
    )


def _write_t_field_3d(path: Path) -> None:
    path.write_text(
        textwrap.dedent(
            """\
            FoamFile
            {
                version     2.0;
                format      ascii;
                class       volScalarField;
                object      T;
            }

            dimensions      [0 0 0 0 0 0 0];
            internalField   uniform 0;

            boundaryField
            {
                inlet_drug   { type fixedValue; value uniform 1; }
                inlet_medium { type fixedValue; value uniform 0; }
                outlet       { type zeroGradient; }
                walls        { type zeroGradient; }
                floor        { type zeroGradient; }
                ceiling      { type zeroGradient; }
            }
            """
        )
    )


def _run_blockmesh_3d(case_dir: Path) -> bool:
    prefix = _find_openfoam_prefix()
    cmd = ["blockMesh"] if not prefix else [prefix, "-c", "blockMesh"]
    try:
        result = subprocess.run(
            cmd, cwd=case_dir, capture_output=True, text=True, check=True, env=os.environ
        )
        (case_dir / "blockMesh.log").write_text(result.stdout + "\n" + result.stderr)
        return True
    except subprocess.CalledProcessError as exc:
        (case_dir / "blockMesh.log").write_text((exc.stdout or "") + "\n" + (exc.stderr or ""))
        return False


def _run_simplefoam_3d(case_dir: Path, timeout: int = SOLVER_TIMEOUT_S) -> bool:
    log_path = case_dir / "simpleFoam.log"
    prefix = _find_openfoam_prefix()
    cmd = ["simpleFoam"] if not prefix else [prefix, "-c", "simpleFoam"]
    try:
        with open(log_path, "w") as log_file:
            subprocess.run(
                cmd, cwd=case_dir, stdout=log_file, stderr=subprocess.STDOUT,
                timeout=timeout, check=True, env=os.environ,
            )
        return _check_residuals(log_path)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False


def _run_postprocess(case_dir: Path, func: str, *, ignore_errors: bool = False) -> bool:
    prefix = _find_openfoam_prefix()
    cmd = ["postProcess", "-func", func, "-latestTime"]
    if prefix:
        cmd = [prefix, "-c", " ".join(cmd)]
    try:
        subprocess.run(cmd, cwd=case_dir, check=True, capture_output=True, env=os.environ)
        return True
    except subprocess.CalledProcessError as exc:
        if not ignore_errors:
            raise
        (case_dir / f"postProcess_{func}.log").write_text(
            (exc.stdout or b"").decode("utf-8", errors="replace")
            + "\n" + (exc.stderr or b"").decode("utf-8", errors="replace")
        )
        return False


def _check_residuals(log_path: Path, threshold: float = 1e-4) -> bool:
    if not log_path.exists():
        return False
    pattern = re.compile(r"final residual\s*=\s*([0-9eE\+\-\.]+)", re.IGNORECASE)
    converged_u, converged_p = False, False
    for line in reversed(log_path.read_text().splitlines()):
        if any(v in line for v in ("Solving for Ux", "Solving for Uy", "Solving for Uz")):
            m = pattern.search(line)
            if m and float(m.group(1)) < threshold:
                converged_u = True
        if "Solving for p" in line:
            m = pattern.search(line)
            if m and float(m.group(1)) < threshold:
                converged_p = True
        if converged_u and converged_p:
            return True
    return False


# ---------------------------------------------------------------------------
# 3D metric extraction
# ---------------------------------------------------------------------------


def _compute_l2_floor_3d(
    case_dir: Path, target_profile: TargetProfile, L: float, W: float
) -> float:
    """Compute L2_to_target on the floor (z ≈ 0 layer) for the 3D case."""
    time_dir = find_latest_time(case_dir)
    if time_dir is None:
        return float("nan")
    t_file = time_dir / "T"
    if not t_file.exists():
        return float("nan")
    centres = read_cell_centres(case_dir)
    C = read_scalar_field(t_file)
    if C.shape[0] != centres.shape[0]:
        return float("nan")
    # Select cells in the lowest z-decile (cell-centre z in [0, H/10]).
    z = centres[:, 2]
    z_min = float(z.min())
    z_max = float(z.max())
    z_thresh = z_min + 0.1 * max(z_max - z_min, 1e-12)
    mask = z <= z_thresh
    if mask.sum() < 10:
        mask = z <= (z_min + 0.3 * (z_max - z_min))
    C_floor = C[mask]
    centres_floor = centres[mask]
    C_target = target_profile.evaluate(centres_floor[:, 0], centres_floor[:, 1], L=L, W=W)
    return float(l2_to_target(C_floor, C_target))


def _floor_wss_statistics(case_dir: Path, mu: float) -> tuple[float, float, float]:
    """Return (mean, max, CV) of ‖τ_wall‖ on the floor patch.

    Falls back to a U-gradient estimate (``τ ≈ μ · |u_t|/z``) at the first
    cell-centre above the floor if the ``wallShearStress`` function object
    was not written.
    """
    time_dir = find_latest_time(case_dir)
    if time_dir is None:
        return float("nan"), float("nan"), float("nan")

    wss_path = time_dir / "wallShearStress"
    if wss_path.exists():
        magnitudes = _parse_floor_wss(wss_path)
        if magnitudes.size > 0:
            # OpenFOAM wallShearStress units are m^2/s^2 = τ/ρ; convert to Pa
            # assuming ρ = 1000 (water/media).  This is consistent with v1.
            tau_Pa = magnitudes * 1000.0
            return (
                float(tau_Pa.mean()),
                float(tau_Pa.max()),
                float(tau_Pa.std() / max(tau_Pa.mean(), 1e-12)),
            )

    # Fallback: first-cell-above-floor tangential velocity gradient.
    U = read_vector_field(time_dir / "U")
    centres = read_cell_centres(case_dir)
    z = centres[:, 2]
    z_min = float(z.min())
    z_thresh = z_min + 0.05 * (float(z.max()) - z_min)
    mask = z <= z_thresh
    if mask.sum() < 10:
        return float("nan"), float("nan"), float("nan")
    u_tan = np.linalg.norm(U[mask, :2], axis=1)
    z_floor = z[mask] - z_min + 1e-9
    tau = mu * u_tan / z_floor
    return float(tau.mean()), float(tau.max()), float(tau.std() / max(tau.mean(), 1e-12))


def _parse_floor_wss(wss_path: Path) -> np.ndarray:
    text = wss_path.read_text()
    patch_match = re.search(r"floor\s*\{(.*?)\n\s*\}", text, flags=re.DOTALL)
    if patch_match is None:
        return np.array([])
    non = re.search(
        r"value\s+nonuniform\s+List<vector>\s+\d+\s*\((.*?)\)\s*;",
        patch_match.group(1),
        flags=re.DOTALL,
    )
    if non is None:
        return np.array([])
    trip = re.findall(r"\(\s*([-+\d.eE]+)\s+([-+\d.eE]+)\s+([-+\d.eE]+)\s*\)", non.group(1))
    if not trip:
        return np.array([])
    vec = np.array([[float(a), float(b), float(c)] for a, b, c in trip])
    return np.linalg.norm(vec, axis=1)


def dump_results(results: List[Result3D], output_path: Path) -> Path:
    """Write a JSON summary of multiple 3D validation runs."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = [r.to_dict() for r in results]
    with open(output_path, "w") as f:
        json.dump(payload, f, indent=2)
    return output_path
